area = input().split(' ')
a = float(area[0])
b = float(area[1])
c = float(area[2])
print(f'TRIANGULO: {(a * c) / 2:.3f}')
print(f'CIRCULO: {3.14159 * (c ** 2):.3f}')
print(f'TRAPEZIO: {((a + b) * c) / 2:.3f}')
print(f'QUADRADO: {b ** 2:.3f}')
print(f'RETANGULO: {a * b:.3f}')
